### ISSUE TITLE
Automatic particle simulation failing (Win10)

### ISSUE THREAD

**Issue by sysu19351158** [cv-rits/rain-rendering#10]
**Hi**
**I am very interested in testing this rendering method on my custom images. So I had installed all the dependencies on Windows10, and tested the command of weather simulator "cd win_x64 & AHLSimulation.exe" successfully.** 

**But when testing the command "python main.py --dataset customdb --intensity 25 --frame_end 10" with the default configuration file customdb.py and default dataset customdb that includes one image and corrsponding depth map, I met the following error.**

Building internal parameters...

Checking sequences...
 1 sequences found: ['first']
Found 1 valid sequence(s): ['first']

Resolving particles simulations...
 No specific simulation settings found for 'first'. Will fallback to database 'customdb' settings, if not intentional this might fails.
 1 particles simulations to compute... Simulations will attempt to run automatically using weather particle simulator
Create thread data\particles\customdb\first\rain\25mm
START thread:  data\particles\customdb\first\rain\25mm
 #0  In main menu
 #0  Apply options: {'cam_hz': 10, 'cam_CCD_WH': [1242, 375], 'cam_CCD_pixsize': 4.65, 'cam_WH': [1242, 375], 'cam_focal': 6, 'cam_gain': 20, 'cam_f_number': 6.0, 'cam_focus_plane': 6.0, 'cam_exposure': 2, 'cam_pos': [1.5, 1.5, 0.3], 'cam_lookat': [1.5, 1.5, -1.0], 'cam_up': [0.0, 1.0, 0.0], 'depth_scale': 1, 'render_scale': 1, 'sim_hz': 2000, 'sim_mode': 'normal', 'sim_duration': 34.0, 'sim_steps': {}, 'sequences': {'seq1': {'sim_mode': 'normal', 'sim_duration': 10}, 'seq2': {'sim_mode': 'steps', 'sim_steps': {'cam_motion': [100.0, 90.0, 80.0, 70.0, 60.0, 50.0, 40.0, 30.0, 20.0, 10.0, 0.0]}}, 'seq3': {'sim_mode': 'steps', 'sim_steps': {'rain_fallrate': [30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]}}}}
Wait for threads
 #0  In main menu
 #0     Save light map
 #0  Deactivating rain particles
 #0  Activating rain particles
 #0  Setting rain fallrate
 #0  In main menu
 #0  Starting simulation
 #0  ERROR occured. Check the content of the log file to solve: data\particles\customdb\first\rain\25mm\automate_log.txt
 #0  <pexpect.popen_spawn.PopenSpawn object at 0x000001B786D15208>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
<pexpect.popen_spawn.PopenSpawn object at 0x000001B786D15208>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
 #0  If starting python from an IDE, check LD_LIBRARY_PATH environment is accessible (https://youtrack.jetbrains.com/issue/PY-29580)
 sim. progress: All threads completed
Wait for threads
Thread ended:  data\particles\customdb\first\rain\25mm
All threads completed
 All particles simulation completed
Something went wrong, cannot locate particles simulation file for sequence first
Might crash later on

**How can I solve it?**

**Comment by sysu19351158** [comment]
Many thanks for your help.

There's nothing wrong with your code. It was my fault that I set the parameter "frame_end" wrong when I run it. Now I run the code successfully on Windows.

Thank you. Best.

**Comment by fanq15** [comment]
Hi, I met the same problem but the solution does not work in my case.

**Comment by rdecharette** [comment]
Hi @fanq15, your issue #12 it is not similar to that one. I'm closing this one that is already solved.
