### ISSUE TITLE
Rain and fog images for cityscapes val and test datasets

### ISSUE THREAD

**Issue by Abhinav-Singhal-8130** [cv-rits/rain-rendering#11]
Hi
I would like to download the rain/fog-augmented images for the cityscapes validation and test datasets also (weather_download-generate.py as mentioned in https://team.inria.fr/rits/computer-vision/weather-augment/ generates the images for only the train images).

Kindly mention the procedure to do so. If that is not possible, I would have to run the particle simulator, but for that, depth maps are needed (but links for only the train depth images have been provided), hence, do give the source of the validation and test cityscapes depth maps. 

Thanks

**Comment by theo2021** [comment]
For the rain follow the steps [here](https://github.com/cv-rits/rain-rendering/issues/3#issuecomment-816472118). Unfortunately for the fog, I would also like some instructions.

**Comment by rdecharette** [comment]
Hello all,

@Abhinav-Singhal-8130 you can actually generate the other sets by following indeed the instructions. This will require a bit of work, but shouldn't be too complex.

@theo2021 the fog code is not public (not clean) but upon request I'm sharing it. You'll get a mail very soon with that.

Best

**Comment by theo2021** [comment]
@rdecharette it would be great if you can send me the code to generate the fog. Thank you!!

**Comment by theo2021** [comment]
Hi @rdecharette  can you send me an email at the end with the code? It would be very helpful

**Comment by rdecharette** [comment]
Hello @theo2021 ,

I sent you a mail already on Jan. 26th 2022 at 12:46:33 (Paris Time). Can you double check ?

**Comment by theo2021** [comment]
Thanks for the reply @rdecharette , I can't find the email, unfortunately, can you send it to theo2021@gmail.com just in case.

**Comment by rdecharette** [comment]
Done. Let me know if you don't receive it.

**Comment by theo2021** [comment]
Thank you, I received the code!

Best,
Theodoros

Στις Τρί 15 Φεβ 2022 στις 11:05 μ.μ., ο/η Raoul de Charette <
***@***.***> έγραψε:

**Comment by 853108389** [comment]
> Hi @rdecharette can you send me an email at the end with the code? It would be very helpful

Excuse me, it would be great if you can send me the code to generate the fog too.

**Comment by mohhef** [comment]
hello @rdecharette  do you mind sharing the code for fog at mohhef@gmail.com, was wondering if its more convenient for you to push it to a separate branch within the same repo

**Comment by rdecharette** [comment]
I just shared it now.
