### ISSUE TITLE
we can not get the kitti test data from the data download link.

### ISSUE THREAD

**Issue by designerZhou** [cv-rits/rain-rendering#13]
![image](https://user-images.githubusercontent.com/24848148/148322594-e5caf1da-dcd5-4446-a942-9c50c6dd963a.png)
please check,
thanks

**Comment by rdecharette** [comment]
Hello designerZhou, 

First, politeness and details are also valued in github request

I've checked, the link does work. Also it is a KITTI website link. If you have problem contact them.

Regards.
