### ISSUE TITLE
Error while generating particle simulation

### ISSUE THREAD

**Issue by TheRealSalvo** [cv-rits/rain-rendering#14]
Hi, I'm trying to generate rain particles for a custom dataset but when i run the following command errors occur:
`$ python main.py --dataset mydb  --intensity 25`

Building internal parameters...

Checking sequences...
 1 sequences found: ['seq1']
Found 1 valid sequence(s): ['seq1']

Resolving particles simulations...
 1 particles simulations to compute... Simulations will attempt to run automatically using weather particle simulator
Create thread data/particles/mydb/seq1/rain/25mm
START thread:  data/particles/mydb/seq1/rain/25mm
 #0  In main menu
 #0  Apply options: {'cam_hz': 10, 'cam_CCD_WH': [1242, 375], 'cam_CCD_pixsize': 4.65, 'cam_WH': [1242, 375], 'cam_focal': 6, 'cam_gain': 20, 'cam_f_number': 6.0, 'cam_focus_plane': 6.0, 'cam_exposure': 2, 'cam_pos': [1.5, 1.5, 0.3], 'cam_lookat': [1.5, 1.5, -1.0], 'cam_up': [0.0, 1.0, 0.0], 'depth_scale': 1, 'render_scale': 1, 'sim_hz': 2000, 'sim_mode': 'normal', 'sim_duration': 10, 'sim_steps': {}}
 #0  In main menu
 #0  	Save light map
 #0  Deactivating rain particles
 #0  Activating rain particles
 #0  Setting rain fallrate
 #0  In main menu
 #0  Starting simulation
Wait for threads
 #0  ERROR occured. Check the content of the log file to solve: data/particles/mydb/seq1/rain/25mm/automate_log.txt
 #0  <pexpect.popen_spawn.PopenSpawn object at 0x7fccf40c8518>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
<pexpect.popen_spawn.PopenSpawn object at 0x7fccf40c8518>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
 #0  If starting python from an IDE, check LD_LIBRARY_PATH environment is accessible (https://youtrack.jetbrains.com/issue/PY-29580)
 sim. progress: All threads completed
Wait for threads
Thread ended:  data/particles/mydb/seq1/rain/25mm
All threads completed
 All particles simulation completed
Something went wrong, cannot locate particles simulation file for sequence seq1
Might crash later on

Running renderers...
Output directory: data/output/mydb

Sequence: seq1
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    generator.run()
  File "/home/salvo/Desktop/rain-rendering/rain-rendering/common/generator.py", line 202, in run
    sim_num = len(self.particles[sequence])
KeyError: 'seq1'

So I think the problem is that the particles dictionary is actually empty because the weather particles generator doesn't produce an output and/or the script cannot find the files needed.
If I run ./AHLSimuation it does not produce any error.
I'm using Ubuntu 20.04 on a virtual machine.
I'm using python in a conda enviroment from terminal.
[automate_log.txt](https://github.com/cv-rits/rain-rendering/files/7921735/automate_log.txt)
[mydb.py](https://github.com/cv-rits/rain-rendering/files/7921752/mydb.txt)

**Comment by TheRealSalvo** [comment]
Found the solution reading closed issue #12

**Comment by rdecharette** [comment]
Great, happy it solved it.
