### ISSUE TITLE
Speed up rendering

### ISSUE THREAD

**Issue by sysu19351158** [cv-rits/rain-rendering#15]
Hi, I am running the code on my custom images. But it is quite slow. In addition to multithreading, is there any way to speed up rendering？

**Comment by rdecharette** [comment]
Hi, sorry for delay I missed this issue. 
Multithreading is the most efficient way actually (check main_threaded.py). Once particles files are generated, rendering speed mainly relates to the fact that simulation accounts for each individual drop FOV. Removing that would significantly speeds up but requires diving in the code, and will reduce quality.
Good luck.
