### ISSUE TITLE
NotADirectoryError: rain_diff folder doesn't exist

### ISSUE THREAD

**Issue by alanMachineLeraning** [cv-rits/rain-rendering#16]
NotADirectoryError: rain_diff folder doesn't exist

**Comment by rdecharette** [comment]
Hello,

Please be respectful and describe your problem if you wish help (what did you download, what is your file structure).
I suspect you have not followed the guidelines corectly.

Regards.

**Comment by alanMachineLeraning** [comment]
1、 I download [rain_diff] dataset of Weather Cityscapes
2、unzip weather_cityscapes_leftImg8bit_train_rain_diff.zip
3、python3 weather_dev_toolkit/weather_generate.py cityscapes --cityscapes_root ../weather_cityscap   
4、get error:
    raise NotADirectoryError("rain_diff folder doesn't exist")
NotADirectoryError: rain_diff folder doesn't exist

**Comment by rdecharette** [comment]
You probably unzipped in the wrong place or provided wrong `cityscapes_root` argument. 
Your directory structure seems incorrect. If I recall correctly, the structure should be:

`%cityscapes_root%/weather_datasets/weather_cityscapes/leftImg8bit/train/rain_diff`
