### ISSUE TITLE
Can you provide the val's Depth Image of Cityscapes Datasets?

### ISSUE THREAD

**Issue by wangm9766** [cv-rits/rain-rendering#2]
Thank you for your code ！
Because there are only Cityscapes Datasets's Train's Depth Image, Can you provide the Cityscapes Datasets's Val's Depth Image, or can you provide the ways to create the Depth Image?

**Comment by rdecharette** [comment]
Hello. Sorry we're not offering all validation depth image on Cityscapes, but you should be able to obtain them easily by running [MonoDepth2](https://github.com/nianticlabs/monodepth2).

**Comment by wangm9766** [comment]
Thank you for your reply!
How did you generate the train's depth image? Running the MonoDepth2?  I want to generate the coincident validation depth image as train depth image.

**Comment by rdecharette** [comment]
Cityscapes train depth images were generated with MonoDepth (v1) and post-processed with a guided filter to align RGB/Depth. 
All details are in sec. 5.1.1 of ICCV paper, and sec. 6.1 of IJCV paper.
