### ISSUE TITLE
Where do I get the ground truth for the object or semantic parsing of the images/sequences?

### ISSUE THREAD

**Issue by flyywh** [cv-rits/rain-rendering#4]
Where do I get the ground truth for the object or semantic parsing of the images/sequences? Thanks!

**Comment by rdecharette** [comment]
Hi.

You should just use the groundtruth of the original sequences. For example for:
kitti/data_object objects labels are [here](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark)
cityscapes/leftImg8bit semantic labels are [here](https://www.cityscapes-dataset.com/downloads/)

Best

**Comment by flyywh** [comment]
Thanks! I also have a question.
Are there labels for the two sequences: raw_data/2011_09_26_drive_0032_sync and raw_data/2011_09_26_drive_0056_sync?
Many thanks!

**Comment by rdecharette** [comment]
Hi. Raw data were used to compose KITTI benchmarks, so you can find some of the labels, but they are not annotated per se. We were using them for qualitative purpose only. Hope this clarifies.
