### ISSUE TITLE
Any future work on LiDAR based rain-rendering

### ISSUE THREAD

**Issue by ammaryasirnaich** [cv-rits/rain-rendering#5]
Hello,  I really appreciate effort and work that is being shared via this repository. I just have a question about any future work for LiDAR based rain-rendering. Is there any work is this part ?

**Comment by rdecharette** [comment]
Hi, thanks always nice to see that it's useful ! That sure is an interesting direction but we haven't planned that for now. This work is doing a similar job though: https://arxiv.org/pdf/2107.07004.pdf

**Comment by ammaryasirnaich** [comment]
Many thanks, @rdecharette I really appreciate for sharing the relevant paper in this direction. It's definitely an interesting work. Best of luck to you and your team for future endeavors.
