### ISSUE TITLE
Generate depth images

### ISSUE THREAD

**Issue by IvanGarcia7** [cv-rits/rain-rendering#6]
How can i generate depth images with python to test your proposal with my own dataset?

**Comment by rdecharette** [comment]
Hello. We have specific instructions to generate on your own dataset in the readme: https://github.com/cv-rits/rain-rendering#rendering-rain-on-custom-images

**Comment by IvanGarcia7** [comment]
Hello. In the case of the generation of images with a specific dataset, it is assumed that depth images are required and it is not established how to generate them.

**Comment by rdecharette** [comment]
Sure we do not detail that that as it is out of the scope of our work. In [our paper](https://drive.google.com/file/d/1TvaOzH8MDpkpkZcAdJdZr0M7CpwTEO5n/view) we use Monodepth or Monodepth 2 but you can use any depth inference algorithm (eg. check [this](https://paperswithcode.com/task/monocular-depth-estimation)) for that.
Hope that helps.

**Comment by IvanGarcia7** [comment]
Thanks for your help!
